version: '3.9'
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  worker:
    build: .
    command: rq worker default
    volumes:
      - .:/app
    depends_on:
      - redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prevengos
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
