version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prevengos-local-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_APP_USER: ${MSSQL_APP_USER}
      MSSQL_APP_PASSWORD: ${MSSQL_APP_PASSWORD}
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver/init-db.sh:/init-db.sh:ro
    command: /bin/bash -c "/init-db.sh & /opt/mssql/bin/sqlservr"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6

  hub-backend:
    build:
      context: ../..
      dockerfile: modules/hub-backend/Dockerfile
    image: prevengos/hub-backend:local
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=${MSSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${MSSQL_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${MSSQL_APP_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "${HUB_PORT:-8080}:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data:
    driver: local
