spring:
  application:
    name: hub-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

hub:
  sqlserver:
    url: jdbc:sqlserver://localhost:1433;databaseName=Prevengos
    username: prevengos
    password: changeit
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jobs:
    rrhh-export:
      base-dir: ${RRHH_EXPORT_BASE:/var/prevengos/oficial/outgoing}
      archive-dir: ${RRHH_EXPORT_ARCHIVE:/var/prevengos/oficial/archive}
      process-name: rrhh
      origin: hub
      operator: hub-system
      cron: 0 0 3 * * *
      lookback-hours: 24
      delivery:
        enabled: true
        protocol: ${RRHH_EXPORT_PROTOCOL:sftp}
        remote-dir: ${RRHH_EXPORT_REMOTE:/prevengos/oficial/rrhh}
        sftp:
          host: ${RRHH_EXPORT_SFTP_HOST:localhost}
          port: ${RRHH_EXPORT_SFTP_PORT:22}
          username: ${RRHH_EXPORT_SFTP_USER:prevengos}
          password: ${RRHH_EXPORT_SFTP_PASSWORD:changeit}
          strict-host-key-checking: ${RRHH_EXPORT_SFTP_STRICT:false}
        smb:
          host: ${RRHH_EXPORT_SMB_HOST:localhost}
          share: ${RRHH_EXPORT_SMB_SHARE:rrhh}
          username: ${RRHH_EXPORT_SMB_USER:prevengos}
          password: ${RRHH_EXPORT_SMB_PASSWORD:changeit}
          domain: ${RRHH_EXPORT_SMB_DOMAIN:}
    rrhh-import:
      inbox-dir: ${RRHH_IMPORT_INBOX:/var/prevengos/oficial/incoming}
      archive-dir: ${RRHH_IMPORT_ARCHIVE:/var/prevengos/oficial/archive}
      error-dir: ${RRHH_IMPORT_ERROR:/var/prevengos/oficial/error}
      process-name: rrhh
      cron: 0 30 3 * * *
      max-drops-per-run: 4

prl:
  notifier:
    enabled: ${PRL_NOTIFIER_ENABLED:false}
    base-url: ${PRL_NOTIFIER_BASE_URL:http://localhost:9000}
    api-token: ${PRL_NOTIFIER_API_TOKEN:}
    events-channel: ${PRL_NOTIFIER_EVENTS_CHANNEL:hub.sync}
    events-webhook: ${PRL_NOTIFIER_EVENTS_WEBHOOK:/api/hooks/hub-sync}
    shared-secret: ${PRL_NOTIFIER_SHARED_SECRET:}

logging:
  level:
    com.prevengos.plug.hubbackend: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
