spring:
  application:
    name: hub-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

hub:
  sqlserver:
    url: jdbc:sqlserver://localhost:1433;databaseName=Prevengos
    username: prevengos
    password: changeit
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jobs:
    rrhh-export:
      base-dir: ${RRHH_EXPORT_BASE:/var/prevengos/oficial/outgoing}
      process-name: rrhh
      cron: 0 0 3 * * *
      lookback-hours: 24
    rrhh-import:
      inbox-dir: ${RRHH_IMPORT_INBOX:/var/prevengos/oficial/incoming}
      archive-dir: ${RRHH_IMPORT_ARCHIVE:/var/prevengos/oficial/archive}
      error-dir: ${RRHH_IMPORT_ERROR:/var/prevengos/oficial/error}
      process-name: rrhh
      cron: 0 30 3 * * *
      max-drops-per-run: 4

logging:
  level:
    com.prevengos.plug.hubbackend: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
