image:
  repository: ghcr.io/prevengos/api-rest
  tag: latest
  pullPolicy: IfNotPresent

env:
  SPRING_PROFILES_ACTIVE: staging
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

secretRefs:
  database:
    name: plug-database
    usernameKey: username
    passwordKey: password
    urlKey: url
  redis:
    name: plug-redis
    urlKey: url

secrets:
  database:
    enabled: false
    username: ""
    password: ""
    url: ""
  redis:
    enabled: false
    url: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: false
  className: nginx
  host: plug-api.prevengos.example
  tlsSecretName: plug-api-tls

persistence:
  volumeMounts: []
  volumes: []
